language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database palette_picker_test;' -U postgres
- npm run migrate
- npm run seed
deploy:
  provider: heroku
  api_key:
    secure: Y67jzDJK1PASMMHHLtl8vK5EojcwZusvGLYjvipvlES261OilnAtqRkqd8+vLLHXq99LzX3+pRWEIo1ICDmm/53rMbfOlcw36myPMFYrub7QJmMqhLZurvkWTAoC0a/BRZxBOAckEfXuud3QPATuvrlLTDKXHvYBJukPl1VwwGQmLbmvuhpXZAAPjc/q+AAUpyNS1kSEL/efgcsATBHOZEFyYBeol2vomg5GWCAIb2SqrTf7Wqt0mQInMKZVhPy9LcAThChUc2/PqHSUNVXtJUud+OgGhBxXKZ10NroI9HiYEl/HinQDLxXcKmcyoX/Ew6g0WfF0oSs/QBgZ325YztD+HDkXZ0EOU5o7q9W8li1RXxzn00+j5VCsWOWDLRQavnvADp1V9IANSl/z+tolKLLOQSH2ZJypjXK/9pn06nSrJvjXg+vHNZgxGS70Yqq5Fv5sVgNp4zHdQprV/LoNBqKgP1a98ocYKSypqfvRG3zoA1MzB1pDrmxoxOpu2k7cYa2MDxIbR/8U5N7SFBj9ZqFyCzL9bGBAsMbu2T9CdYrQS2v9rJwk09hzyeV1j/PYq3E6SW3gBgmF+FSi8kZLjHXtJBOTFw/jgW65z/BLWUQEW7zAJEwt/Aw64+zTWQ02UDKvOrfrwwC5EKy7gh9tRGwhKCb2YI/VC2DWJCukFTY=
  app: palette-picker-jd
